name: Set up test project
description: Set up the test project fixture

runs:
  # `node18` isn't supported yet
  using: node16
  main: 'setUpTestProject.mjs'

inputs:
  test-project-path:
    description: Path to the test project
