name: 'Set up test project'
description: 'Set up the test project fixture'
outputs:
  TEST_PROJECT_PATH:
    description: 'Path to the test project'
runs:
  # `node18` isn't supported yet
  using: node16
  main: 'setUpTestProject.mjs'
