name: 🧶 Set up job
description: |
  Set up Node.js and caching for yarn, then install

inputs:
  node-version:
    default: 18

  github-token:
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: ⬢ Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    # We try to cache and restore yarn's cache directory and install state to speed up the yarn install step.
    # Caching yarn's cache directory avoids its fetch step.
    #
    # See:
    # - https://gist.github.com/belgattitude/042f9caf10d029badbde6cf9d43e400a
    # - https://github.com/yarnpkg/berry/discussions/2621
    - name: 📁 Get yarn cache directory
      id: get-yarn-cache-directory
      run: echo "CACHE_DIRECTORY=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    # If the primary key doesn't match, the cache will probably be stale or incomplete, but still worth restoring.
    - name: ♻️ Restore yarn cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-yarn-cache-directory.outputs.CACHE_DIRECTORY }}
        key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: yarn-cache-${{ runner.os }}

    - name: ♻️ Restore yarn install state
      uses: actions/cache@v3
      with:
        path: .yarn/install-state.gz
        key: yarn-install-state-${{ runner.os }}-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: yarn-install-state-${{ runner.os }}

    - name: ♻️ Restore node_modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: yarn-node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: yarn-node-modules-${{ runner.os }}

    # `--inline-builds` is only for debugging. It tells Yarn to print the output of dependencies' build steps instead of writing them to files
    # See https://yarnpkg.com/cli/install#options-inline-builds.
    # We include the GitHub token to avoid rate limiting when installing `@vscode/ripgrep`.
    - name: 🐈 Yarn install
      run: yarn install --inline-builds
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
