name: Set up job
description: >
  Everything you need to run a job in CI.
  Checkout this repo (redwoodjs/redwood), set up Node.js, yarn install, and build.

inputs:
  set-up-yarn-cache:
    description: >
      For some actions, setting up the yarn cache takes longer than it would to just yarn install.
    required: false
    default: true

  yarn-install-directory:
    description: >
      The directory to run `yarn install` in.
    required: false

  build:
    description: >
      Whether or not to run `yarn build` to build all the framework packages.
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: ⬢ Enable Corepack
      shell: bash
      run: corepack enable

    - name: ⬢ Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # We have to enable Corepack again for Windows. 🤷
    # In general, we're waiting on [this issue](https://github.com/actions/setup-node/issues/531)
    # to be resolved so that `actions/setup-node@v4` has first-class Corepack support.
    - name: ⬢ Enable Corepack
      if: runner.os == 'Windows'
      shell: bash
      run: corepack enable

    - name: 🐈 Set up yarn cache
      if: inputs.set-up-yarn-cache == 'true'
      uses: ./.github/actions/set-up-yarn-cache

    # One of our dependencies is on GitHub instead of NPM and without authentication
    # we'll get rate limited and this step becomes flaky.
    - name: 🐈 Yarn install
      shell: bash
      working-directory: ${{ inputs.yarn-install-directory }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: yarn install --inline-builds

    - name: 🏗️ Build
      if: inputs.build == 'true'
      shell: bash
      run: yarn build
