name: 🧶 Set up job
description: |
  Set up node and yarn cache, then install. This sequence of steps appeared often enough
  in many of Redwood's jobs to make it worth abstracting.

inputs:
  node-version:
    default: 18
  github-token:
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: ⬢ Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    # From https://github.com/actions/cache/blob/main/examples.md#node---yarn-2.
    - name: 📁 Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
