name: 💬 Message Slack Package Publishing
description: Send an npm publishing message to Slack
inputs:
  title:
    description: title
    required: true
  status:
    description: status
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - debug:
      run |
        echo ${{ toJSON(github) }}
        echo ${{ toJSON(github.event) }}

    - name: Get status emoji
      id: get-status-emoji
      uses: sergeysova/jq-action@v2.2.1
      with:
        cmd: 'echo "{ \"success\": \"✅\", \"failure\": \"🚨\" }" | jq .${{ inputs.status }} -r'

    - name: 💬 Message Slack
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "title": "${{ inputs.title }}",
            "status": "${{ steps.get-status-emoji.outputs.value }} ${{ inputs.status }}",
            "version": "${{ inputs.version }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PACKAGE_PUBLISHING }}
