name: 🤖 Approve and merge release PR

on:
  pull_request_target:
    branches: [release]
    types: [opened]

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  auto-approve-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v2

      - name: Enable auto-merge
        uses: reitermarkus/automerge@main
        with:
          token: ${{ secrets.JTOAR_TOKEN }}
          merge-method: squash
          required-labels: cherry-pick
          pull-request: ${{ github.event.inputs.pull-request }}
