name: Check test project fixture

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

# Cancel in-progress runs of this workflow.
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  YARN_ENABLE_HARDENED_MODE: 0
  YARN_ENABLE_IMMUTABLE_INSTALLS: 0

jobs:
  check-test-project-fixture:
    name: Check test project fixture
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up job
        uses: ./.github/actions/set-up-job
        with:
          yarn-install-directory: .github/scripts
          build: false

      - name: Check test project fixture
        working-directory: .github/scripts
        # This is to get colors in the output.
        # See https://github.com/chalk/supports-color/issues/106.
        env:
          FORCE_COLOR: 2
        run: yarn tsx checkTestProjectFixture.mts
