# When a PR is merged into the main branch, this workflow tries to cherry pick the squashed commit into the release branch using:
#
# ```
# git switch release
# git cherry-pick --ff $GITHUB_SHA
# ```
#
# Which cherry picks the squashed commit into the release branch, "fast forwarding" if it can, keeping the history the same.
#
# If it can't fast forward (i.e. main and release have diverged), it'll open PR against release with the squashed commit.
# See the end of ci.yml for that.

name: 🍒 Cherry pick into release branch

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cherry-pick-fast-forward:
    name: ⏩ Cherry pick fast forward
    runs-on: ubuntu-latest

    # Don't cherry pick commits with breaking changes.
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'release:feature-breaking') }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: release

      - name: ⏩ Cherry pick fast forward
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git cherry-pick --ff $GITHUB_SHA

          # If the HEAD of main and release point to the same commit, then the fast forward worked.
          if [[ "$(git rev-parse origin/main)" = "$(git rev-parse release)" ]]; then
            git push
          else
            exit 1
          fi

  cherry-pick-into-release-pr:
    name:  Cherry pick PR
    runs-on: ubuntu-latest

    needs: cherry-pick-fast-forward
    if: ${{ failure() }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into release PR
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.2
        with:
          # We specify a token because we want other workflows (like CI) to run on this PR.
          # If we omit this, it uses the default token (GITHUB_TOKEN) which doesn't trigger other workflows.
          token: ${{ secrets.JTOAR_TOKEN }}
          branch: release
          labels: cherry-pick
