on:
  workflow_run:
    workflows: ["⚙️ CI"]
    types: [completed]
    # branches: [release]

jobs:
  cherry-pick:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: cherry-pick
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ contains(github.event.pull_request.labels.*.name, 'cherry-pick') }}"

      - uses: actions/checkout@v3
        with:
          ref: release
          # git isn't able to work with the $GITHUB_SHA if we don't checkout everything.
          fetch-depth: 0
          # Since release is a protected branch, we need a token to run git push later.
          token: ${{ secrets.JTOAR_TOKEN }}

      - name: 🍒 Cherry pick
        run: |
          git cherry-pick ${{ github.event.pull_request.head.ref }}
          git push

      - name: Close PR
        env:
          GH_TOKEN: ${{ secrets.JTOAR_TOKEN }}
        run: |
          gh api graphql -F id=${{ github.event.pull_request.node_id }} -f query='
            mutation($id: ID!) {
              closePullRequest(input: {
                pullRequestId: $id
              }) {
                clientMutationId
              }
            }
          '
