name: 🦜 Publish Canary

on:
  push:
    branches: [main, next]
    tags-ignore: ['v**']
    # No need to run on docs-only changes
    paths-ignore: ['docs/**']

jobs:
  publish-canary:
    name: 🦜 Publish Canary
    # if: github.repository == 'redwoodjs/redwood'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.value }}
    steps:
      - name: ⏹️ Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - uses: actions/checkout@v3
        # `fetch-depth`—number of commits to fetch. `0` fetches all history for all branches and tags.
        #  This is required because lerna uses tags to determine the version
        with:
          fetch-depth: 0

      # - name: 🧶 Setup job
      #   uses: ./.github/actions/setup_job

      # - name: ✅ Check constraints, dependencies, and package.json's
      #   uses: ./tasks/check

      # - name: 🏗 Build
      #   run: yarn build

      # - name: 🔎 Lint
      #   run: yarn lint

      # - name: 🧪 Test
      #   run: yarn test

      # - name: Get publish flags
      #   id: get-publish-flags
      #   uses: ./.github/actions/get_publish_flags

      # - name: 🚢 Publish
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc

      #     yarn lerna publish ${{ steps.get-publish-flags.outputs.flags }}
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: echo "${{ toJSON(github) }}"
      - run: echo "${{ toJSON(github.event) }}"

      - name: 🏷 Get version
        id: get-version
        uses: sergeysova/jq-action@v2.2.1
        with:
          cmd: 'jq .version packages/core/package.json -r'

  message-slack:
    name: 💬 Message Slack
    needs: publish-canary
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 💬 Message Slack
        uses: ./.github/actions/message_slack_publishing
        with:
          title: "🦜 Canary Packages"
          status: ${{ needs.publish-canary.result }}
          version: ${{ needs.publish-canary.outputs.version }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_PACKAGE_PUBLISHING }}
