name: 🚩 Require milestone

on:
  pull_request:
    types: [opened, synchronize, reopened, milestoned, demilestoned]

# Cancel in-progress runs of this workflow.
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  YARN_ENABLE_HARDENED_MODE: 0

jobs:
  require-milestone:
    name: 🚩 Require milestone
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up job
        uses: ./.github/actions/set-up-job
        with:
          set-up-yarn-cache: false
          yarn-install-directory: .github/scripts
          build: false

      - name: Require milestone
        working-directory: .github/scripts
        # This is to get colors in the output.
        # See https://github.com/chalk/supports-color/issues/106.
        env:
          FORCE_COLOR: 2
        run: yarn tsx requireMilestone.mts
