name: 🤘 Deploy Baremetal

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

jobs:
  deploy-baremetal:
    # if: github.repository == 'redwoodjs/deploy-target-ci'

    name: test
    runs-on: ubuntu-latest

    env:
      REDWOOD_CI: 1

    steps:
      - run: echo "yo"

  message-slack:
    needs: deploy-baremetal
    if: always()

    name: 💬 Message Slack
    runs-on: ubuntu-latest

    steps:
      - name: Get `deploy_status`
        run: |
          RW_DEPLOY_STATUS=$(echo '{
            "failure": "Deploy failed 🚨",
            "success": "Deploy successful ✅",
            "cancelled": "Deploy cancelled 🔘",
            "skipped": "Deploy skipped 🔘"
            }' | \
              jq -r .${{ needs.deploy-baremetal.result }}
          )

          echo "RW_DEPLOY_STATUS=$RW_DEPLOY_STATUS" >> $GITHUB_ENV

      - name: Get `deploy_commit`
        run: |
          RW_DEPLOY_COMMIT=$(echo '${{ github.event.head_commit.message }}' | awk 'NR==1 {print}')
          echo $RW_DEPLOY_COMMIT >> $GITHUB_ENV

      # - name: 💬 Message Slack
      #   uses: slackapi/slack-github-action@v1
      #   with:
      #     payload: |
      #       {
      #         "deploy_target": "Baremetal 🤘",
      #         "deploy_status": "$RW_DEPLOY_STATUS",
      #         "deploy_commit": "$RW_DEPLOY_COMMIT"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
